## ┌────────────────────────────────────────────────────────────────────────────┐
## │ <DF>                                                                       │
##
## Symbolic definitions of a bunch of useful terminal colour escape codes.

ANSI_ESCAPE="\033"
ANSI_RESET="${ANSI_ESCAPE}[00m"

ANSI_COLOUR_DEFAULT="[39m"

ANSI_COLOUR_BLACK="[30m"
ANSI_COLOUR_RED="[31m"
ANSI_COLOUR_GREEN="[32m"
ANSI_COLOUR_YELLOW="[33m"
ANSI_COLOUR_BLUE="[34m"
ANSI_COLOUR_MAGENTA="[35m"
ANSI_COLOUR_CYAN="[36m"
ANSI_COLOUR_GREY="[37m"

ANSI_COLOUR_LIGHT_BLACK="[90m"
ANSI_COLOUR_LIGHT_RED="[91m"
ANSI_COLOUR_LIGHT_GREEN="[92m"
ANSI_COLOUR_LIGHT_YELLOW="[93m"
ANSI_COLOUR_LIGHT_BLUE="[94m"
ANSI_COLOUR_LIGHT_MAGENTA="[95m"
ANSI_COLOUR_LIGHT_CYAN="[96m"
ANSI_COLOUR_LIGHT_GREY="[97m"

demo_colours()
{
    echo -e ${ANSI_ESCAPE}${ANSI_COLOUR_DEFAULT}ANSI_COLOUR_DEFAULT${ANSI_RESET}

    echo -e ${ANSI_ESCAPE}${ANSI_COLOUR_BLACK}ANSI_COLOUR_BLACK${ANSI_RESET}
    echo -e ${ANSI_ESCAPE}${ANSI_COLOUR_RED}ANSI_COLOUR_RED${ANSI_RESET}
    echo -e ${ANSI_ESCAPE}${ANSI_COLOUR_GREEN}ANSI_COLOUR_GREEN${ANSI_RESET}
    echo -e ${ANSI_ESCAPE}${ANSI_COLOUR_YELLOW}ANSI_COLOUR_YELLOW${ANSI_RESET}
    echo -e ${ANSI_ESCAPE}${ANSI_COLOUR_BLUE}ANSI_COLOUR_BLUE${ANSI_RESET}
    echo -e ${ANSI_ESCAPE}${ANSI_COLOUR_MAGENTA}ANSI_COLOUR_MAGENTA${ANSI_RESET}
    echo -e ${ANSI_ESCAPE}${ANSI_COLOUR_CYAN}ANSI_COLOUR_CYAN${ANSI_RESET}
    echo -e ${ANSI_ESCAPE}${ANSI_COLOUR_GREY}ANSI_COLOUR_GREY${ANSI_RESET}

    echo -e ${ANSI_ESCAPE}${ANSI_COLOUR_LIGHT_BLACK}ANSI_COLOUR_LIGHT_BLACK${ANSI_RESET}
    echo -e ${ANSI_ESCAPE}${ANSI_COLOUR_LIGHT_RED}ANSI_COLOUR_LIGHT_RED${ANSI_RESET}
    echo -e ${ANSI_ESCAPE}${ANSI_COLOUR_LIGHT_GREEN}ANSI_COLOUR_LIGHT_GREEN${ANSI_RESET}
    echo -e ${ANSI_ESCAPE}${ANSI_COLOUR_LIGHT_YELLOW}ANSI_COLOUR_LIGHT_YELLOW${ANSI_RESET}
    echo -e ${ANSI_ESCAPE}${ANSI_COLOUR_LIGHT_BLUE}ANSI_COLOUR_LIGHT_BLUE${ANSI_RESET}
    echo -e ${ANSI_ESCAPE}${ANSI_COLOUR_LIGHT_MAGENTA}ANSI_COLOUR_LIGHT_MAGENTA${ANSI_RESET}
    echo -e ${ANSI_ESCAPE}${ANSI_COLOUR_LIGHT_CYAN}ANSI_COLOUR_LIGHT_CYAN${ANSI_RESET}
    echo -e ${ANSI_ESCAPE}${ANSI_COLOUR_LIGHT_GREY}ANSI_COLOUR_LIGHT_GREY${ANSI_RESET}
}

##
## │ </DF>                                                                      │
## └────────────────────────────────────────────────────────────────────────────┘
